/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appunidad1;

import CapaNegocio.clsCliente;
import CapaNegocio.clsCuota;
import CapaNegocio.clsProducto;
import CapaNegocio.clsVenta;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import sun.management.jdp.JdpPacket;

/*
 INTEGRANTES:
   - BENEL RAMIREZ, Sara
   - CASTRO FERNANDEZ, Paola   
   - VILCHEZ VILLEGAS, José Carlos
   - YOMONA PARRAGUEZ, Cinthya
*/

public class JDVentas extends javax.swing.JDialog {

    clsCliente objCliente = new clsCliente();
    clsVenta objVenta = new clsVenta();
    clsProducto objProducto = new clsProducto();
    
    DefaultTableModel modelo = new DefaultTableModel();
    
    float subTotal;
    int op = -1;
    int codUser = 0;

    /**
     * Creates new form JDVentas
     */
    public JDVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        grpDocumento.add(rbtBoleta);
        grpDocumento.add(rbtFactura);
        deshabilitar();
        generarCodigo();
        modelo.addColumn("CÓDIGO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("P UNITARIO");
        modelo.addColumn("DESCUENTO");
        modelo.addColumn("NUEVO PRECIO");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("SUBTOTAL");
        tblProductos.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpDocumento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodVenta = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnAnadir = new javax.swing.JButton();
        contenedorScroll = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        rbtBoleta = new javax.swing.JRadioButton();
        rbtFactura = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        txtSubTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtIgv = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModDesc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".:Registrar Venta:.");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Empresa de Ventas");

        jLabel2.setText("\"VENDEDORES SAC\"");

        jLabel3.setText("Documento N°");

        txtCodVenta.setEditable(false);
        txtCodVenta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTitulo.setText("DOCUMENTO DE VENTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(61, 61, 61)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCodVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        jPanel2.setBackground(new java.awt.Color(222, 227, 218));

        jLabel4.setText("DNI/RUC:");

        jLabel5.setText("Nombre:");

        txtDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDocumentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDocumentoFocusLost(evt);
            }
        });
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });
        txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyReleased(evt);
            }
        });

        jLabel6.setText("Dirección:");

        jLabel8.setText("Productos:");

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        btnAnadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/mas.png"))); // NOI18N
        btnAnadir.setText("Añadir Producto");
        btnAnadir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        contenedorScroll.setViewportView(tblClientes);

        rbtBoleta.setText("Boleta");
        rbtBoleta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtBoletaStateChanged(evt);
            }
        });
        rbtBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtBoletaActionPerformed(evt);
            }
        });

        rbtFactura.setText("Factura");
        rbtFactura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtFacturaStateChanged(evt);
            }
        });
        rbtFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFacturaActionPerformed(evt);
            }
        });

        jLabel7.setText("Código:");

        jLabel9.setText("Tipo Cliente:");

        txtSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel10.setText("SUBTOTAL:");

        txtIgv.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel11.setText("IGV:");

        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel12.setText("TOTAL:");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/save.png"))); // NOI18N
        btnGuardar.setText("Guardar con pago");
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/eliminar.png"))); // NOI18N
        btnQuitar.setText("Quitar Producto");
        btnQuitar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/modificar.png"))); // NOI18N
        btnModificar.setText("Modificar Cant");
        btnModificar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/salir.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnModDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/modificar.png"))); // NOI18N
        btnModDesc.setText("Modificar Desc");
        btnModDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModDescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(contenedorScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                                        .addComponent(txtDireccion)
                                        .addComponent(txtDocumento)
                                        .addComponent(txtCod)
                                        .addComponent(txtTipo)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(btnAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnModDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                        .addComponent(txtIgv)
                                        .addComponent(txtTotal))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(rbtBoleta)
                        .addGap(18, 18, 18)
                        .addComponent(rbtFactura)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtBoleta)
                    .addComponent(rbtFactura))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(contenedorScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnadir)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btnModificar))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtIgv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuitar)
                    .addComponent(btnModDesc))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(jLabel12)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        // TODO add your handling code here:
        JDAñadirProductos objAnaProd = new JDAñadirProductos((Frame) SwingUtilities.getWindowAncestor(this), true);
        objAnaProd.setLocationRelativeTo(this);
        objAnaProd.setVisible(true);
        int producto = objAnaProd.getCod();
        int cantidad = objAnaProd.getCant();
        int descuento = objAnaProd.getDesc();
        agregarProducto(producto, cantidad, descuento);
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        listarClientes();
    }//GEN-LAST:event_formWindowActivated

    private void txtDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyReleased
        // TODO add your handling code here:
        if(txtDocumento.getText().length()>0 && evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(modelo.getRowCount()==2 && ((rbtBoleta.isSelected() && txtDocumento.getText().length()==8) || (rbtFactura.isSelected() && txtDocumento.getText().length()==11))){
                llenarDatos(txtDocumento.getText());
            }else{
                JOptionPane.showMessageDialog(rootPane, "El documento ingresado no existe");
                limpiarControles();
            }
        }
        listarClientes();
    }//GEN-LAST:event_txtDocumentoKeyReleased
    
    private void rbtBoletaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtBoletaStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtBoletaStateChanged

    private void rbtFacturaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtFacturaStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtFacturaStateChanged

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        // TODO add your handling code here:
        if(tblClientes.getSelectedRow()==0){
            JDMantenimientoCliente objMantCliente = new JDMantenimientoCliente((Frame) SwingUtilities.getWindowAncestor(this), true);
            objMantCliente.setLocationRelativeTo(this);
            objMantCliente.setVisible(true);
        }else{
            String doc = "null";
            if(rbtBoleta.isSelected()){
                doc = String.valueOf(tblClientes.getValueAt(tblClientes.getSelectedRow(), 0));
            }else{
                doc = String.valueOf(tblClientes.getValueAt(tblClientes.getSelectedRow(), 1));
            }
            llenarDatos(doc);
        }
    }//GEN-LAST:event_tblClientesMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            objVenta.registrar(Integer.parseInt(txtCodVenta.getText()), Float.parseFloat(txtTotal.getText()), Float.parseFloat(txtSubTotal.getText()), Float.parseFloat(txtIgv.getText()), rbtBoleta.isSelected(), Integer.parseInt(txtCod.getText()), tblProductos);
            JOptionPane.showMessageDialog(rootPane, "Venta Registrada Correctamente");
            limpiarControles();
            generarCodigo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void rbtBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtBoletaActionPerformed
        // TODO add your handling code here:
        if(rbtBoleta.isSelected()){
            lblTitulo.setText("BOLETA DE VENTA");
            habilitar();
            if(txtDocumento.getText().length()==11){
                String dni="null";
                try {
                    ResultSet rs = objCliente.verificarDocumento(codUser);
                    while (rs.next()){
                        if(rs.getString("dni")==null){
                            rbtFactura.setSelected(true);
                        }
                        llenarDatos(rs.getString("dni")==null?"null":rs.getString("dni"));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_rbtBoletaActionPerformed
    
    private void rbtFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFacturaActionPerformed
        // TODO add your handling code here:
        if(rbtFactura.isSelected()){
            lblTitulo.setText("FACTURA");
            habilitar();
            if(txtDocumento.getText().length()==8){
                String ruc="null";
                try {
                    ResultSet rs = objCliente.verificarDocumento(codUser);
                    while (rs.next()){
                        if(rs.getString("ruc")==null){
                            rbtBoleta.setSelected(true);
                        }
                        llenarDatos(rs.getString("ruc")==null?"null":rs.getString("ruc"));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_rbtFacturaActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        tblProductos.setEnabled(true);
        tblProductos.setRowSelectionAllowed(true);
        desBotones();
        btnCancelar.setEnabled(true);
        op=1;
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        if (tblProductos.isEnabled()){
            if(op==1){
                int rpta = JOptionPane.showConfirmDialog(rootPane, "Seguro que desea eliminar "+ String.valueOf(tblProductos.getValueAt(tblProductos.getSelectedRow(), 1)), "SISTEMA", JOptionPane.YES_NO_OPTION);
                if (rpta == 0 ){
                    modelo.removeRow(tblProductos.getSelectedRow());
                }
            }else if(op==0){
                try {
                    String rpta = String.valueOf(JOptionPane.showInputDialog(rootPane, "Ingrese la nueva cantidad para " + String.valueOf(tblProductos.getValueAt(tblProductos.getSelectedRow(), 1)), String.valueOf(tblProductos.getValueAt(tblProductos.getSelectedRow(), 5))));
                    if (!rpta.equals("null")){
                        int ctd = Integer.parseInt(rpta);
                        if (ctd > 0 ){
                            int prod = Integer.parseInt(String.valueOf(tblProductos.getValueAt(tblProductos.getSelectedRow(), 0)));
                            
                            int stock = objProducto.getStock(prod);
                            if(ctd <= stock){
                                String descpor = String.valueOf(tblProductos.getValueAt(tblProductos.getSelectedRow(), 3));
                                int desc = Integer.parseInt(descpor.substring(0, descpor.length()-1));
                                modelo.removeRow(tblProductos.getSelectedRow());
                                agregarProducto(prod, ctd, desc);
                            }else{
                                JOptionPane.showMessageDialog(rootPane, "Stock Insuficiente");
                            }
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "El registro ha sido eliminado");
                            modelo.removeRow(tblProductos.getSelectedRow());
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Cantidad no válida");
                }
            }else if(op==2){
                try {
                    String descpor = String.valueOf(tblProductos.getValueAt(tblProductos.getSelectedRow(), 3));
                    String rpta = (JOptionPane.showInputDialog(rootPane, "Ingrese el nuevo descuento para " + String.valueOf(tblProductos.getValueAt(tblProductos.getSelectedRow(), 1)), descpor.substring(0, descpor.length()-1)));
                    if (rpta != null){
                        int desc = Integer.parseInt(rpta);
                        if (desc >= 0 ){
                            int prod = Integer.parseInt(String.valueOf(tblProductos.getValueAt(tblProductos.getSelectedRow(), 0)));
                            int cant = Integer.parseInt(String.valueOf(tblProductos.getValueAt(tblProductos.getSelectedRow(), 5)));
                            modelo.removeRow(tblProductos.getSelectedRow());
                            agregarProducto(prod, cant, desc);
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "El registro ha sido eliminado");
                            modelo.removeRow(tblProductos.getSelectedRow());
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Cantidad no válida");
                }
            }
            calcularTotal();
            tblProductos.setRowSelectionAllowed(false);
            tblProductos.setEnabled(false);
            btnCancelarActionPerformed(null);
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        tblProductos.setRowSelectionAllowed(false);
        tblProductos.setEnabled(false);
        habBotones();
        btnCancelar.setEnabled(false);
        if(tblProductos.getRowCount()>0){
            btnModificar.setEnabled(true);
            btnQuitar.setEnabled(true);
            btnGuardar.setEnabled(true);
            btnModDesc.setEnabled(true);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarControles();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        tblProductos.setEnabled(true);
        tblProductos.setRowSelectionAllowed(true);
        desBotones();
        btnCancelar.setEnabled(true);
        op=0;
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtDocumentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDocumentoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoFocusGained

    private void txtDocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDocumentoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoFocusLost

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void btnModDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModDescActionPerformed
        // TODO add your handling code here:
        tblProductos.setEnabled(true);
        tblProductos.setRowSelectionAllowed(true);
        desBotones();
        btnCancelar.setEnabled(true);
        op=2;
    }//GEN-LAST:event_btnModDescActionPerformed

    private void listarClientes(){
        
        ResultSet rsClientes = null;
        try {
            rsClientes = objCliente.filtrarClientes(txtDocumento.getText());
            DefaultTableModel modelo = new DefaultTableModel();
            
            modelo.addColumn("DNI");
            modelo.addColumn("RUC");
            modelo.addColumn("NOMBRE");
            
            modelo.addRow(new Object[]{"+ REGISTRAR"});
            
            while(rsClientes.next()){
                modelo.addRow(new Object[]{rsClientes.getString("dni"), rsClientes.getString("ruc"), rsClientes.getString("nombres")});
            }
            tblClientes.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    
    public void llenarDatos(String doc){
        if(doc.equals("null")){
            int rpta = JOptionPane.showConfirmDialog(rootPane, "El usuario no cuenta con el Documento Necesario, ¿Desea Agregarlo?", "SISTEMA", JOptionPane.YES_NO_OPTION);
            if (rpta==0){
                JDMantenimientoCliente objMantCliente = new JDMantenimientoCliente((Frame) SwingUtilities.getWindowAncestor(this), true);
                objMantCliente.setLocationRelativeTo(this);
                objMantCliente.setVisible(true);
            }
        }else{
            txtDocumento.setText(doc);
            try {
                ResultSet rs = objCliente.buscarCliente(doc);
                while(rs.next()){
                    txtCod.setText(rs.getString("codcliente"));
                    codUser = rs.getInt("codcliente");
                    txtNombre.setText(rs.getString("nombres"));
                    txtDireccion.setText(rs.getString("direccion"));
                    txtTipo.setText(rs.getString("nombre"));
                    listarClientes();
                }
                habBotones();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        }
    }
    
    public void generarCodigo(){
        try {
            int cod = objVenta.generarCodigoVenta();
            txtCodVenta.setText(String.valueOf(cod));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    
    public void agregarProducto(int producto, int cantidad, int descuento){
        if(producto!=0 && cantidad!=0){
            ResultSet rs = null;
            try {
                tblProductos.setModel(modelo);
                
                boolean repetido = false;
                int fila = -1;
                for (int i=0; i<tblProductos.getRowCount(); i++){
                    if(Integer.parseInt(String.valueOf(tblProductos.getValueAt(i, 0))) == producto){
                        repetido = true;
                        fila = i;
                    }
                }
                if (repetido){
                    int aux = Integer.parseInt(String.valueOf(tblProductos.getValueAt(fila, 5)));
                    cantidad += aux;
                    modelo.removeRow(fila);
                }
                
                int stock = objProducto.getStock(producto);
                if(cantidad > stock){
                    cantidad = stock;
                    JOptionPane.showMessageDialog(rootPane, "Stock Insuficiente");
                }
                
                rs = objProducto.buscarProducto(producto);
                
                while(rs.next()){
                    modelo.addRow(new Object[]{rs.getString("codproducto"), rs.getString("nomproducto"), rs.getString("precio"), descuento+"%", rs.getFloat("precio")-descuento*rs.getFloat("precio")/100,cantidad, (cantidad * (rs.getFloat("precio")-descuento*rs.getFloat("precio")/100))});
                }
                btnQuitar.setEnabled(true);
                btnModificar.setEnabled(true);
                btnGuardar.setEnabled(true);
                btnModDesc.setEnabled(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        }
        calcularTotal();
    }
    
    public void calcularTotal(){
        try{
            subTotal=0;
            for(int i=0; i<tblProductos.getRowCount(); i++){
                subTotal += Float.parseFloat(String.valueOf(tblProductos.getValueAt(i, 4)));
            }
            float igv = (float) (subTotal * 0.18);
            txtIgv.setText(String.valueOf(igv));
            txtSubTotal.setText(String.valueOf(subTotal));
            txtTotal.setText(String.valueOf(subTotal+igv));
        }catch(Exception e){
        }
    }
       
    public void deshabilitar(){
        txtDocumento.setEnabled(false);
        txtCod.setEnabled(false);
        txtCod.setEditable(false);
        txtNombre.setEnabled(false);
        txtNombre.setEditable(false);
        txtDireccion.setEnabled(false);
        txtDireccion.setEditable(false);
        txtTipo.setEnabled(false);
        txtTipo.setEditable(false);
        contenedorScroll.setVisible(false);
        txtSubTotal.setEnabled(false);
        txtSubTotal.setEditable(false);
        txtIgv.setEnabled(false);
        txtIgv.setEditable(false);
        txtTotal.setEnabled(false);
        txtTotal.setEditable(false);
        desBotones();
    }
    
    public void habilitar(){
        txtDocumento.setEnabled(true);
        txtCod.setEnabled(true);
        txtNombre.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtTipo.setEnabled(true);
        contenedorScroll.setVisible(true);
        txtIgv.setEnabled(true);
        txtSubTotal.setEnabled(true);
        txtTotal.setEnabled(true);
    }
    
    public void habBotones(){
        btnAnadir.setEnabled(true);
        //btnGuardar.setEnabled(true);
        btnLimpiar.setEnabled(true);
    }
    
    public void desBotones(){
        btnAnadir.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnQuitar.setEnabled(false);
        btnLimpiar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnModDesc.setEnabled(false);
    }
    
    public void limpiarControles(){
        txtDocumento.setText("");
        listarClientes();
        txtCod.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTipo.setText("");
        int cant = modelo.getRowCount();
        for (int i=0; i<cant; i++){
            modelo.removeRow(0);
        }
        txtIgv.setText("0.0");
        txtSubTotal.setText("0.0");
        txtTotal.setText("0.0");
        desBotones();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDVentas dialog = new JDVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModDesc;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JScrollPane contenedorScroll;
    private javax.swing.ButtonGroup grpDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbtBoleta;
    private javax.swing.JRadioButton rbtFactura;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCodVenta;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtIgv;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
