package CapaPresentacion;

import CapaNegocio.clsUsuario;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 INTEGRANTES:
   - BENEL RAMIREZ, Sara
   - CASTRO FERNANDEZ, Paola   
   - VILCHEZ VILLEGAS, José Carlos
   - YOMONA PARRAGUEZ, Cinthya
 */

public class JFPrincipal extends javax.swing.JFrame implements Runnable{
    
    Thread hilo;
    String user;
    String nomUsuario;
    clsUsuario objUsuario = new clsUsuario();
    boolean sesion = false;
    String cargo;
    
    public JFPrincipal() {
        initComponents();
        lblUsuario.setText("");
        lblDatosSesion.setText("");
        this.setExtendedState(MAXIMIZED_BOTH);
        hilo = new Thread(this);
        hilo.start();
        iniciarSesion();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }
    
    //Cambiart el icono de un formulario
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("src/icon1.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem12 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        btnLogin = new javax.swing.JButton();
        btnContraseña = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnConsultar = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDatosSesion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmLogin = new javax.swing.JMenu();
        jmiCambiarUsuario = new javax.swing.JMenuItem();
        jmiCambiarContraseña = new javax.swing.JMenuItem();
        jmiCerrarSesion = new javax.swing.JMenuItem();
        jmiMisDatos = new javax.swing.JMenuItem();
        jmMantenimiento = new javax.swing.JMenu();
        jmiUsuario = new javax.swing.JMenuItem();
        jmiMarca = new javax.swing.JMenuItem();
        jmiCategoria = new javax.swing.JMenuItem();
        jmiProducto = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmnVentas = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuPagarVenta = new javax.swing.JMenuItem();
        mnuPagoCredito = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmAlmacen = new javax.swing.JMenu();
        jmiRegistrarCompra = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        mnuCreditosClientes = new javax.swing.JMenuItem();
        mnuVentasDiarias = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jmReportes = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        mnuReporteVentasDiarias = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnuVentasDiarias = new javax.swing.JMenuItem();
        mnuCreditosClientes = new javax.swing.JMenuItem();
        //jMenuItem14 = new javax.swing.JMenuItem();
        jmiRegistrarCompra = new javax.swing.JMenuItem();

        jMenuItem12.setText("jMenuItem12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".:SISTEMA DE COMERCIALIZACIÓN:.");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/chang_user.png"))); // NOI18N
        btnLogin.setToolTipText("Cambiar usuario");
        btnLogin.setFocusable(false);
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setPreferredSize(new java.awt.Dimension(50, 39));
        btnLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogin);

        btnContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/changeuser.png"))); // NOI18N
        btnContraseña.setToolTipText("Cambiar Contraseña");
        btnContraseña.setFocusable(false);
        btnContraseña.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContraseña.setPreferredSize(new java.awt.Dimension(50, 39));
        btnContraseña.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContraseñaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnContraseña);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/logout.png"))); // NOI18N
        btnCerrar.setFocusable(false);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setPreferredSize(new java.awt.Dimension(50, 39));
        btnCerrar.setToolTipText("Cerrar Sesión");
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCerrar);
        jToolBar1.add(jSeparator1);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/consultar.png"))); // NOI18N
        btnConsultar.setToolTipText("Consultar Productos");
        btnConsultar.setFocusable(false);
        btnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar.setPreferredSize(new java.awt.Dimension(50, 39));
        btnConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConsultar);

        btnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/vender.png"))); // NOI18N
        btnVenta.setToolTipText("Registrar Venta");
        btnVenta.setFocusable(false);
        btnVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVenta.setPreferredSize(new java.awt.Dimension(50, 39));
        btnVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVenta);

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/cliente.png"))); // NOI18N
        btnCliente.setToolTipText("Registrar Cliente");
        btnCliente.setFocusable(false);
        btnCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCliente.setPreferredSize(new java.awt.Dimension(50, 39));
        btnCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCliente);

        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/pago.png"))); // NOI18N
        btnPagar.setToolTipText("Registrar Pago");
        btnPagar.setFocusable(false);
        btnPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPagar.setPreferredSize(new java.awt.Dimension(50, 39));
        btnPagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPagar);
        jToolBar1.add(jSeparator2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setText("   ");
        jPanel3.add(jLabel7);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/miniuser.png"))); // NOI18N
        jLabel1.setText("Usuario:  ");
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel3.add(jLabel1);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsuario.setText("User");
        lblUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(lblUsuario);

        jLabel2.setText("   ");
        jPanel3.add(jLabel2);

        lblDatosSesion.setText("--");
        jPanel3.add(lblDatosSesion);

        jPanel1.add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/calendario.png"))); // NOI18N
        jLabel5.setText("Fecha:  ");
        jPanel4.add(jLabel5);

        lblFecha.setText("NULL");
        jPanel4.add(lblFecha);

        jLabel10.setText("   ");
        jPanel4.add(jLabel10);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/clock.png"))); // NOI18N
        jLabel6.setText("Hora:  ");
        jPanel4.add(jLabel6);

        lblHora.setText("NULL");
        jPanel4.add(lblHora);

        jLabel11.setText("   ");
        jPanel4.add(jLabel11);

        lblCargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCargo.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(lblCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);

        jPanel5.setBackground(new java.awt.Color(222, 227, 218));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/android2.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jmLogin.setText("Login");

        jmiCambiarUsuario.setText("Cambiar Usuario");
        jmiCambiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCambiarUsuarioActionPerformed(evt);
            }
        });
        jmLogin.add(jmiCambiarUsuario);

        jmiCambiarContraseña.setText("Cambiar Contraseña");
        jmiCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCambiarContraseñaActionPerformed(evt);
            }
        });
        jmLogin.add(jmiCambiarContraseña);

        jmiCerrarSesion.setText("Cerrar Sesión");
        jmiCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCerrarSesionActionPerformed(evt);
            }
        });
        jmLogin.add(jmiCerrarSesion);

        jmiMisDatos.setText("Mis Datos");
        jmiMisDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMisDatosActionPerformed(evt);
            }
        });
        jmLogin.add(jmiMisDatos);

        jMenuBar1.add(jmLogin);

        jmMantenimiento.setText("Mantenimiento");

        jmiUsuario.setText("Usuarios");
        jmiUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsuarioActionPerformed(evt);
            }
        });
        jmMantenimiento.add(jmiUsuario);

        jmiMarca.setText("Marca");
        jmiMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMarcaActionPerformed(evt);
            }
        });
        jmMantenimiento.add(jmiMarca);

        jmiCategoria.setText("Categoría");
        jmiCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCategoriaActionPerformed(evt);
            }
        });
        jmMantenimiento.add(jmiCategoria);

        jmiProducto.setText("Producto");
        jmiProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProductoActionPerformed(evt);
            }
        });
        jmMantenimiento.add(jmiProducto);

        jMenuItem5.setText("Parámetros");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmMantenimiento.add(jMenuItem5);

        jMenuBar1.add(jmMantenimiento);

        jmnVentas.setText("Ventas");

        jMenuItem9.setText("Gestionar Cliente");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jmnVentas.add(jMenuItem9);

        jMenuItem10.setText("Registrar Venta");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jmnVentas.add(jMenuItem10);

        jMenu5.setText("Registrar Pago");

        mnuPagarVenta.setText("Pagar Venta");
        mnuPagarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPagarVentaActionPerformed(evt);
            }
        });
        jMenu5.add(mnuPagarVenta);

        mnuPagoCredito.setText("Pagar Cuotas");
        mnuPagoCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPagoCreditoActionPerformed(evt);
            }
        });
        jMenu5.add(mnuPagoCredito);

        jmnVentas.add(jMenu5);

        jMenuItem13.setText("Consultar Caja");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jmnVentas.add(jMenuItem13);

        jMenuItem2.setText("Cambiar Producto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmnVentas.add(jMenuItem2);

        jMenuItem3.setText("Devolver Venta");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmnVentas.add(jMenuItem3);

        jMenuBar1.add(jmnVentas);

        jmAlmacen.setText("Almacén");

        jmiRegistrarCompra.setText("Registrar Compra");
        jmiRegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistrarCompraActionPerformed(evt);
            }
        });
        jmAlmacen.add(jmiRegistrarCompra);

        jMenuBar1.add(jmAlmacen);

        jmConsultas.setText("Consultas");

        jMenuItem8.setText("Consultar Producto");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jmConsultas.add(jMenuItem8);

        mnuCreditosClientes.setText("Creditos de clientes");
        mnuCreditosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCreditosClientesActionPerformed(evt);
            }
        });
        jmConsultas.add(mnuCreditosClientes);

        mnuVentasDiarias.setText("Ventas diarias");
        mnuVentasDiarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentasDiariasActionPerformed(evt);
            }
        });
        jmConsultas.add(mnuVentasDiarias);

        jMenuItem15.setText("Ventas Por Rango de Fechas");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jmConsultas.add(jMenuItem15);

        jMenuItem4.setText("Estadísticas de Ventas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jmConsultas.add(jMenuItem4);

        jMenuBar1.add(jmConsultas);

        jmReportes.setText("Reportes");

        jMenuItem16.setText("Reporte listado de Clientes");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jmReportes.add(jMenuItem16);

        mnuReporteVentasDiarias.setText("Reporte de ventas diarias");
        mnuReporteVentasDiarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporteVentasDiariasActionPerformed(evt);
            }
        });
        jmReportes.add(mnuReporteVentasDiarias);

        jMenuItem1.setText("Reporte de Existencias");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmReportes.add(jMenuItem1);

        jMenuItem6.setText("Reporte de Reponer Ticket");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jmReportes.add(jMenuItem6);


        mnuVentasDiarias.setText("Ventas diarias");
        mnuVentasDiarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentasDiariasActionPerformed(evt);
            }
        });
        //jMenu6.add(mnuVentasDiarias);

        mnuCreditosClientes.setText("Creditos de clientes");
        mnuCreditosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCreditosClientesActionPerformed(evt);
            }
        });
        //jMenu6.add(mnuCreditosClientes);

        //jMenuItem14.setText("Consultar Caja");
        /*jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });*/
        //jMenu6.add(jMenuItem14);

        //jmReportes.add(jMenu6);

        jMenuBar1.add(jmReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        cerrarSesion();
        iniciarSesion();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int rpta = JOptionPane.showConfirmDialog(rootPane, "¿Seguro que desea Salir?", "SISTEMA", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        if(rpta==0){
            cerrarSesion();
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        int rpta = JOptionPane.showConfirmDialog(rootPane, "¿Seguro que desea Salir?", "SISTEMA", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        if(rpta==0){
            cerrarSesion();
            System.exit(0);
        }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jmiCambiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCambiarUsuarioActionPerformed
        // TODO add your handling code here:
        cerrarSesion();
        iniciarSesion();
    }//GEN-LAST:event_jmiCambiarUsuarioActionPerformed

    private void jmiCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCerrarSesionActionPerformed
        // TODO add your handling code here:
        int rpta = JOptionPane.showConfirmDialog(rootPane, "¿Seguro que desea Salir?", "SISTEMA", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        if(rpta==0){
            cerrarSesion();
            System.exit(0);
        }
    }//GEN-LAST:event_jmiCerrarSesionActionPerformed

    private void jmiCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCambiarContraseñaActionPerformed
        // TODO add your handling code here:
        cambiarContraseña();
    }//GEN-LAST:event_jmiCambiarContraseñaActionPerformed

    private void btnContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContraseñaActionPerformed
        // TODO add your handling code here:
        cambiarContraseña();
    }//GEN-LAST:event_btnContraseñaActionPerformed

    private void jmiMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMarcaActionPerformed
        // TODO add your handling code here:
        JDMantenimientoMarca objMantMarca = new JDMantenimientoMarca(this, true);
        objMantMarca.setLocationRelativeTo(this);
        objMantMarca.setVisible(true);
    }//GEN-LAST:event_jmiMarcaActionPerformed

    private void jmiCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCategoriaActionPerformed
        // TODO add your handling code here:
        JDMantenimientoCategoria objMantCategoria = new JDMantenimientoCategoria(this, true);
        objMantCategoria.setLocationRelativeTo(this);
        objMantCategoria.setVisible(true);
    }//GEN-LAST:event_jmiCategoriaActionPerformed

    private void jmiProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductoActionPerformed
        // TODO add your handling code here:
        JDMantenimientoProducto objMantProducto = new JDMantenimientoProducto(this, true);
        objMantProducto.setLocationRelativeTo(this);
        objMantProducto.setVisible(true);
    }//GEN-LAST:event_jmiProductoActionPerformed

    private void jmiUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsuarioActionPerformed
        // TODO add your handling code here:
        JDMantenimientoUsuario objMantUsuario = new JDMantenimientoUsuario(this, true);
        objMantUsuario.setUser(user);
        if (!cargo.equalsIgnoreCase("Gerente General")){
            objMantUsuario.modoPerfil(user);
            //objMantUsuario.setSize(objMantUsuario.getWidth(), objMantUsuario.getSizePerfil());
        }
        objMantUsuario.setLocationRelativeTo(this);
        objMantUsuario.setVisible(true);
    }//GEN-LAST:event_jmiUsuarioActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        JDConsultas objConsultas = new JDConsultas(this, true);
        objConsultas.setLocationRelativeTo(this);
        objConsultas.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        JDMantenimientoCliente objMantCliente = new JDMantenimientoCliente(this, true);
        objMantCliente.setLocationRelativeTo(this);
        objMantCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        JDVentas objVentas = new JDVentas(this, true);
        objVentas.setLocationRelativeTo(this);
        objVentas.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void mnuPagoCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPagoCreditoActionPerformed
        // TODO add your handling code here:
        JDPagoCuotas objpago = new JDPagoCuotas(this,true);
        objpago.setLocationRelativeTo(this);
        objpago.setVisible(true);
    }//GEN-LAST:event_mnuPagoCreditoActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        JDConsultasCaja obj = new JDConsultasCaja(this, true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        JDMantenimientoCliente objMantCliente = new JDMantenimientoCliente(this, true);
        objMantCliente.setLocationRelativeTo(this);
        objMantCliente.setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        JDConsultas objConsultas = new JDConsultas(this, true);
        objConsultas.setLocationRelativeTo(this);
        objConsultas.setVisible(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void mnuVentasDiariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentasDiariasActionPerformed
        // TODO add your handling code here:
        JDVentasDiarias obj = new JDVentasDiarias(this, true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_mnuVentasDiariasActionPerformed

    private void mnuCreditosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCreditosClientesActionPerformed
        // TODO add your handling code here:
        JDCreditosCliente obj = new JDCreditosCliente(this, true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_mnuCreditosClientesActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        JDVentasPorFechas obj = new JDVentasPorFechas(this, true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        FrmReporteClienteListado obj = new FrmReporteClienteListado();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void mnuReporteVentasDiariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporteVentasDiariasActionPerformed
        // TODO add your handling code here:
        JDReporteVentasDiarias obj = new JDReporteVentasDiarias(this, true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_mnuReporteVentasDiariasActionPerformed

    private void mnuPagarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPagarVentaActionPerformed
        // TODO add your handling code here:
        JDPagarVenta obj = new JDPagarVenta(this, true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_mnuPagarVentaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JDReporteExistenciaProductos obj = new JDReporteExistenciaProductos(this, true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        // TODO add your handling code here:
        JDVentas objVentas = new JDVentas(this, true);
        objVentas.setLocationRelativeTo(this);
        objVentas.setVisible(true);
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        JDPagarVenta obj = new JDPagarVenta(this, true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_btnPagarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JDCambiarProducto obj = new JDCambiarProducto(this, true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JDDevolucionVenta obj = new JDDevolucionVenta(this, true);
        obj.setUser(user);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JDEstadisticasVenta obj = new JDEstadisticasVenta(this, true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JDMantenimientoParametros obj = new JDMantenimientoParametros(this, true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jmiRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistrarCompraActionPerformed
        // TODO add your handling code here:
        JDRegistrarCompra obj = new JDRegistrarCompra(this, true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiRegistrarCompraActionPerformed

    private void jmiMisDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMisDatosActionPerformed
        // TODO add your handling code here:
        jmiUsuarioActionPerformed(null);
    }//GEN-LAST:event_jmiMisDatosActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        JDBuscarVentas obj = new JDBuscarVentas(this, true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    void iniciarSesion(){
        try {
            JDInicioSesion objLogin = new JDInicioSesion(this, rootPaneCheckingEnabled);
            objLogin.setLocationRelativeTo(null);
            objLogin.setVisible(true);
            nomUsuario = objLogin.getNombreUsuario();
            user = objLogin.getUsername();
            sesion = objLogin.getValue();
            String datosSesion = objLogin.getDatosSesion();
            lblDatosSesion.setText(datosSesion);
            cargo = objUsuario.privilegios(user);                        
            
            if(sesion){
                lblUsuario.setText(nomUsuario);
                if (cargo.equalsIgnoreCase("Gerente General")) {
                    jmiCambiarContraseña.setVisible(true);
                    jmiCambiarUsuario.setVisible(true);
                    jmiCerrarSesion.setVisible(true);
                    jmMantenimiento.setVisible(true);
                    jmiMisDatos.setVisible(false);
                    jmnVentas.setVisible(true);
                    jmConsultas.setVisible(true);
                    jmReportes.setVisible(true);
                    jmAlmacen.setVisible(true);
                    btnContraseña.setVisible(true);                
                    btnConsultar.setVisible(true);
                    btnVenta.setVisible(true);
                    btnPagar.setVisible(true);
                    btnCliente.setVisible(true);               
                }
                if (cargo.equalsIgnoreCase("Supervisor")) {
                    jmiCambiarContraseña.setVisible(true);
                    jmiCambiarUsuario.setVisible(true);
                    jmiCerrarSesion.setVisible(true);
                    jmMantenimiento.setVisible(true);
                    jmiMisDatos.setVisible(true);
                    jmiUsuario.setVisible(false);
                    jmnVentas.setVisible(true);
                    jmConsultas.setVisible(true);
                    jmReportes.setVisible(true);
                    jmAlmacen.setVisible(false);
                    btnContraseña.setVisible(true);                
                    btnConsultar.setVisible(true);
                    btnVenta.setVisible(true);
                    btnPagar.setVisible(true);
                    btnCliente.setVisible(true); 
                }

                if (cargo.equalsIgnoreCase("Vendedor")) {
                    jmiCambiarContraseña.setVisible(true);
                    jmiCambiarUsuario.setVisible(true);
                    jmiCerrarSesion.setVisible(true);
                    jmMantenimiento.setVisible(false);
                    jmiMisDatos.setVisible(true);
                    jmnVentas.setVisible(true);
                    jmConsultas.setVisible(true);
                    jmReportes.setVisible(false);
                    jmAlmacen.setVisible(false);
                    btnContraseña.setVisible(false);                
                    btnConsultar.setVisible(true);
                    btnVenta.setVisible(false);
                    btnPagar.setVisible(true);
                    btnCliente.setVisible(false);   
                }

                if (cargo.equalsIgnoreCase("Almacenero")) {
                    jmiCambiarContraseña.setVisible(true);
                    jmiCambiarUsuario.setVisible(true);
                    jmiCerrarSesion.setVisible(true);
                    jmMantenimiento.setVisible(false);
                    jmiMisDatos.setVisible(true);
                    jmnVentas.setVisible(false);
                    jmConsultas.setVisible(false);
                    jmReportes.setVisible(true);
                    jmAlmacen.setVisible(true);
                    btnContraseña.setVisible(true);                
                    btnConsultar.setVisible(true);
                    btnVenta.setVisible(false);
                    btnPagar.setVisible(false);
                    btnCliente.setVisible(false); 
                }
                
                if (cargo.equalsIgnoreCase("")) {
                    jmiCambiarContraseña.setVisible(false);
                    jmiCambiarUsuario.setVisible(true);
                    jmiCerrarSesion.setVisible(false);
                    jmMantenimiento.setVisible(false);
                    jmiMisDatos.setVisible(false);
                    jmnVentas.setVisible(false);
                    jmConsultas.setVisible(false);
                    jmReportes.setVisible(false);
                    jmAlmacen.setVisible(false);
                    btnContraseña.setVisible(false);                
                    btnConsultar.setVisible(false);
                    btnVenta.setVisible(false);
                    btnPagar.setVisible(false);
                    btnCliente.setVisible(false);                
                }
                lblCargo.setText(cargo);
            }else{
                JOptionPane.showMessageDialog(rootPane, "No ha iniciado Sesión, No puede acceder a la Aplicación", "ERROR", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        } catch (Exception ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void cerrarSesion(){
        try {
            objUsuario.registrarCierre(user);
            lblUsuario.setText("");
            lblDatosSesion.setText("");
            sesion = false;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    void cambiarContraseña(){
        try {
            String clave = JOptionPane.showInputDialog(rootPane, "Necesitamos verificar que eres tú \nEscribe tu Contraseña Actual", "Cambiar contraseña", JOptionPane.PLAIN_MESSAGE);
            if (clave != null){
                String acceso = objUsuario.login(user, clave);
                if(acceso.equals("")){
                    JOptionPane.showMessageDialog(rootPane, "La contraseña es incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
                    cambiarContraseña();
                }else{
                    JDCambiarContraseña objCambiarContraseña = new JDCambiarContraseña(this, rootPaneCheckingEnabled);
                    objCambiarContraseña.setLocationRelativeTo(null);
                    objCambiarContraseña.setUser(user);
                    objCambiarContraseña.setNecesario(false);
                    objCambiarContraseña.setVisible(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    void privilegios(String nomUser){
        try {
            
        } catch (Exception e) {
        }
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnContraseña;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu jmAlmacen;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenu jmLogin;
    private javax.swing.JMenu jmMantenimiento;
    private javax.swing.JMenu jmReportes;
    private javax.swing.JMenuItem jmiCambiarContraseña;
    private javax.swing.JMenuItem jmiCambiarUsuario;
    private javax.swing.JMenuItem jmiCategoria;
    private javax.swing.JMenuItem jmiCerrarSesion;
    private javax.swing.JMenuItem jmiMarca;
    private javax.swing.JMenuItem jmiMisDatos;
    private javax.swing.JMenuItem jmiProducto;
    private javax.swing.JMenuItem jmiRegistrarCompra;
    private javax.swing.JMenuItem jmiUsuario;
    private javax.swing.JMenu jmnVentas;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblDatosSesion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem mnuCreditosClientes;
    private javax.swing.JMenuItem mnuPagarVenta;
    private javax.swing.JMenuItem mnuPagoCredito;
    private javax.swing.JMenuItem mnuReporteVentasDiarias;
    private javax.swing.JMenuItem mnuVentasDiarias;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Thread current = Thread.currentThread();
        while (current == hilo){
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy");
            SimpleDateFormat formatoHora = new SimpleDateFormat("hh:mm a");
            lblFecha.setText(formatoFecha.format(new Date()));
            lblHora.setText(formatoHora.format(new Date()));
        }
    }
}
